app/models.py
from app import db 

class Task(db.Model): #db.model -> telling that convert this class with an actual database
    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(100), nullable = False)
    status = db.Column(db.String(20), default = "Pending")

app/__init__.py
from flask import Flask #to create the app
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy() #global object of sqlalchemy

def create_app(): #function that we create the app(it will return the app)
    app = Flask(__name__) #creating the app

    app.config['SECRET_KEY'] = 'your-secret-key' #use to secure flash, session
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///todo.db' #db url to tell where is the db
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.__init__(app) 
    #linked the db with app

    from app.models import Task
 #what task should created when run bd.create
    
    with app.app_context():
        db.create_all()

    #bluprint -> routes will be inside it, registred it so that flask will know about tham
    from app.routes.auths import auth_bp
    from app.routes.tasks import tasks_bp
    app.register_blueprint(auth_bp) #calling 
    app.register_blueprint(tasks_bp)

    return app #returning the app

app/routes/auths.py
from flask import Blueprint, session, flash, render_template, redirect, url_for, request

auth_bp = Blueprint("auth", __name__)

user_credantial = {
    'username':'admit',
    'password':'pass'
}

@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")

        if username == user_credantial["username"] and password == user_credantial["password"]:
            session['user'] = username
            flash('Login successful', 'success')
            return redirect(url_for('task.view_task'))
        else:
            flash('Invalide username, password', 'danger')
    return render_template("login.html")

@auth_bp.route("/logout")
def logout():
    session.pop('user', None)
    flash('Logged out', 'info')
    return redirect(url_for("auth.login"))



#blueprint -> all routes will be in a group

app/routes/tasks.py
from flask import Blueprint, render_template, session, redirect, url_for, flash, request
from app import db 
# from app.routes import auths
# importing database object to save task and remove tasks

from app.models import Task
 # task is a model class where we will store the tasks

tasks_bp = Blueprint("task", __name__) #ceating blueprint, "task"-> name of bluepring

@tasks_bp.route("/") #to view the tasks
def view_task():
    if 'user' not in session: #if user is not login
        return redirect(url_for("auth.login")) 
    
    tasks = Task.query.all() #patching all the tasks 
    return render_template('tasks.html', task_list=tasks) #sending tasks to tasks.html

@tasks_bp.route("/add", methods=["POST"]) # To add task, post -> becouse user will send something
def add():
    if 'user' not in session:
        return redirect(url_for("auth.login"))
    
    title = request.form.get("title") #title of the task ,that user wants to add
    if title:
        new_task = Task(title=title, status='Pending') #title(variable of title)=title(new task)
        db.session.add(new_task) #added
        db.session.commit() #saving
        flash('Task added successfully', 'success')

    return redirect(url_for('task.view_task'))

@tasks_bp.route("/toggle/<int:task_id>", methods=["POST"])
def toggle_status(task_id):
    task = Task.query.get(task_id)
    if task:
        if task.status == 'Pending':
            task.status = 'Working'
        elif task.status == 'Working':
            task.status = 'Done'
        else:
            task.status = 'Pending'
        db.session.commit()
    return redirect(url_for('task.view_task'))

@tasks_bp.route('/clear', methods=["POST"])
def clear_tasks():
    Task.query.delete()
    db.session.commit()
    flash('All tasks cleared!', 'info')
    return redirect(url_for('task.view_task'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}To-Do App{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">
</head>
<body>
    <header>
        <div class="container">
            <h2>My To-Do App</h2>

            <nav>
                <a href="{{ url_for('task.view_task') }}">Home</a>
                {% if 'user' in session %}
                    <a href="{{ url_for('auth.logout') }}">Logout</a>
                {% else %}
                    <a href="{{ url_for('auth.login') }}">Login</a>
                {% endif %}

            </nav>
        </div>
    </header>

    <main>
        <div class="container">
            {% with messages = get_flashed_messages(with_categories = True) %}
                {% for category, message in messages %}
                    <div class="flash {{category}}">{{message}}</div>
                {% endfor %}
            {% endwith %}
        </div>
    </main>

    {% block content %}{% endblock %}

    <footer>
        <div class="container">
            <p>&copy; {{2025}} My Flask To-Do App</p>
        </div>
    </footer>
    
</body>
</html>

app/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}

    <div class="login-box">

        <h2>Login</h2>

        <form method="POST" action="{{ url_for('auth.login') }}">
            <div class="form-group">

                <label for="username">Username</label>
                <input type="text" id="username" name="username" placeholder="enter username" required>

            </div>
            <div class="form-group">

                <label for="pass">Password</label>
                <input type="password" id="pass" name="password" placeholder="enter password" required>

            </div>

            <button type="submit" class="btn">Login</button>

        </form>
    </div>
    
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block title %}Registration{% endblock %}

{% block content %}
    <div class="register-box">
        <h2>Registration</h2>
        <h2>Comming soon..........</h2>
    </div>
{% endblock %}

app/templates/tasks.html
{% extends "base.html" %}

{% block title %} Tasks {% endblock %}

{% block content %}
    <div class="task-box">
        <h1>Tasks</h1>
        
        <form action="{{ url_for('task.add') }}" method="POST" class="task-form">

            <input type="text" name="title" placeholder="new task" required>

            <button type="submit" class="btn">Add</button>
        </form>

        {% if task_list %}
            <form method="post" action="{{ url_for('task.clear_tasks') }}">
                <button type="submit" class="btn btn-clear">Clear all tasks</button>
            </form>

            <br>
            <table class="task-table">
                <thead>
                    <tr>
                        <th>Tasks</th>
                        <th>Status</th>
                        <th>Change</th>
                    </tr>
                </thead>

                <tbody>
                    {% for task in task_list %}
                        <tr>
                            <td>{{ loop.index }}</td>
                            <td>{{ task.title }}</td>
                            <td>
                                <span class="badge {{ task.status|lower }}">{{task.status}}</span>
                            </td>
                            <td>
                                <form action="{{ url_for('task.toggle_status', task_id = task.id) }}" method="POST">
                                    <button class="btn-smal" type="submit">Next</button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
        <p>No task yet. Add one above!</p> 
        {% endif %}   

    </div>

{% endblock %}